server:
  port: 9020
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: michael
    password: michael
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: MySQL5DialectUTF8
    show-sql: false
  application:
    name: scs-data-hateoas
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%logger{15}){cyan} - %msg%n'
  level:
    jdbc:
      sqltiming: INFO
      sqlonly: WARN
      audit: WARN
      resultset: WARN
      resultsettable: WARN
      connection: WARN
    org:
      springframework:
        boot: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
