server:
  port: 9010
management:
  security:
    enabled: false
  context-path: /
  endpoints:
    web:
      exposure:
        include: info,health,beans,prometheus,service-registry,hystrix.stream
spring:
  application:
    name: scs-consumer-feign
  profiles:
    active: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8081/eureka/
# Hystrix支持，如果为true，hystrix库必须在classpath中
feign:
  hystrix:
    enabled: true
#hystrix: command: say-hello: execution: timeout: enabled: false
hystrix:
  threadpool:
    default:
      coreSize: 50
  config:
    stream:
      maxConcurrentConnections: 10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
        timeout:
          enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000
